# Generated by Django 3.2.3 on 2022-11-22 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_auto_20221113_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_loading', models.BooleanField(default=False)),
                ('taxi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxi.taxi')),
            ],
        ),
    ]
